### ISSUE TITLE
Feature Request: Pull to refresh

### ISSUE THREAD

**Issue by PatrickNorton** [simanerush/hacker-news-app#1]
At the moment, the only way (as far as I can tell) to refresh the list of stories is to exit out of the app and restart it. It would be nice if the app implemented [pull-to-refresh](https://en.wikipedia.org/wiki/Pull-to-refresh) in order to reload the stories.

**Comment by simanerush** [comment]
Good observation. I'll try to add that

**Comment by PatrickNorton** [comment]
It seems to work! Thanks :)
